/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef ST7789_Interface_H
#define ST7789_Interface_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "lpspi_master_driver.h"
#include "lpspi_slave_driver.h"
#include "lpspi_shared_function.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
/*! @brief Device instance number */
#define INST_ST7789_INTERFACE  1U

/*******************************************************************************
 * Global variables 
 ******************************************************************************/
/* Define state structure for current SPI instance */
extern  lpspi_state_t ST7789_InterfaceState;

/* LPSPI Master Configurations 0 */
extern const lpspi_master_config_t ST7789_SPI_Config;


void GB_MA_SPI_send_byte_conti(uint8_t *val, uint8_t count, uint32_t timeout);

uint8_t GB_MA_SPI_exchange_byte(uint8_t *val, uint8_t count);

#endif /* ST7789_Interface_H */
