/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v10.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_lpuart_1.h"

/*******************************************************************************
 * lpuart_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lpuart_1'
- type: 'lpuart_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpuart'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART_0'
- config_sets:
  - lpuart_driver:
    - lpuart_state_name: 'lpUartState0'
    - lpuart_configuration:
      - 0:
        - name: 'lpuart_0_InitConfig0'
        - readonly: 'true'
        - transferType: 'LPUART_USING_INTERRUPTS'
        - baudRate: '9600'
        - parityMode: 'LPUART_PARITY_DISABLED'
        - stopBitCount: 'LPUART_ONE_STOP_BIT'
        - bitCountPerChar: 'LPUART_8_BITS_PER_CHAR'
        - rxDMAChannel: '0'
        - txDMAChannel: '0'
    - quick_selection: 'dv_lpuart0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
lpuart_state_t lpUartState0;

const lpuart_user_config_t lpuart_0_InitConfig0 = {
  .transferType = LPUART_USING_INTERRUPTS,
  .baudRate = 9600UL,
  .parityMode = LPUART_PARITY_DISABLED,
  .stopBitCount = LPUART_ONE_STOP_BIT,
  .bitCountPerChar = LPUART_8_BITS_PER_CHAR,
  .rxDMAChannel = 0UL,
  .txDMAChannel = 0UL
};
static uint16_t size_of_command( const char* gb_string)
{
	uint16_t counter=0;
	while(*gb_string)
	{
		counter = counter+1;
		*gb_string++;
	}
	return counter;
}
void GB_printString0(const char *gb_myString)
{
	//HAL_UART_Transmit(&huart1,(uint8_t *)gb_myString,size_of_command(gb_myString), 100);


	LPUART_DRV_SendDataBlocking(INST_LPUART_1,(uint8_t *)gb_myString, size_of_command(gb_myString), 100);

	//LPUART_DRV_SendDataPolling
}

void GB_decimel0(uint32_t gb_val)
{
	unsigned char gb_buf[5];
	int8_t gb_ptr;
	for(gb_ptr=0;gb_ptr<5;++gb_ptr) {
		gb_buf[gb_ptr] = (gb_val % 10) + '0';
		gb_val /= 10;
	}
	for(gb_ptr=4;gb_ptr>0;--gb_ptr) {
		if (gb_buf[gb_ptr] != '0') break;
	}
	for(;gb_ptr>=0;--gb_ptr) {

		LPUART_DRV_SendDataBlocking(INST_LPUART_1,&gb_buf[gb_ptr],1, 100);

		//HAL_UART_Transmit(&huart1,&gb_buf[gb_ptr],1, 100);
		//GB_UART_TxChar0(gb_buf[gb_ptr]);
	}
}
/* USER CODE END 0 */



