/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef lpspi_1_H
#define lpspi_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "lpspi_master_driver.h"
#include "lpspi_slave_driver.h"
#include "lpspi_shared_function.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
/*! @brief Device instance number */
#define INST_LPSPI_1  0U
//#define gb_MFRC522_CE_pin_low LPSPI_DRV_SetPcs(0, LPSPI_PCS0, LPSPI_ACTIVE_LOW) //Slave select pin LOW
//
//#define gb_MFRC522_CE_pin_high    LPSPI_DRV_SetPcs(0, LPSPI_PCS0, LPSPI_ACTIVE_HIGH)//Slave select pin HIGH

/*******************************************************************************
 * Global variables 
 ******************************************************************************/
/* Define state structure for current SPI instance */
extern  lpspi_state_t lpspi_1State;

/* LPSPI Master Configurations 0 */
extern const lpspi_master_config_t lpspi_0_MasterConfig0;

/* LPSPI Master Configurations 1 */
extern const lpspi_master_config_t lpspi_0_MasterConfig1;

void GB_MA_SPI0_send_byte_conti(uint8_t val);

uint8_t GB_MA_SPI0_exchange_byte(uint8_t val);

#endif /* lpspi_1_H */
